In [1]:
import json
import pandas as pd
import pickle

In [2]:
import pickle

import os

with open("./raw_data/allActsPDF.pickle", "rb") as file:
    data = pickle.load(file)

df = pd.json_normalize(data)
df

,act.type,act.value,title.type,title.value,publicationDate.type,publicationDate.value,entryintoforce.type,entryintoforce.value,typeDoc.type,typeDoc.xml:lang,typeDoc.value,fileUrl.type,fileUrl.value
0,uri,https://fedlex.data.admin.ch/eli/oc/1/82_69_80,literal,Trattato d'estradizione tra la Svizzera e l'Im...,literal,1874-06-03,literal,1874-06-03,literal,it,Trattato internazionale bilaterale,NaN,NaN
1,uri,https://fedlex.data.admin.ch/eli/oc/18/654_588...,literal,Ordinanza concernente la consegna e il control...,literal,1901-04-19,literal,1901-04-19,literal,it,Ordinanza del Consiglio federale,NaN,NaN
2,uri,https://fedlex.data.admin.ch/eli/oc/18/865_796...,literal,Ordinanza del 9 novembre 1901 sull'esercizio d...,literal,1901-11-09,literal,1901-11-09,literal,it,Ordinanza del Consiglio federale,NaN,NaN
3,uri,https://fedlex.data.admin.ch/eli/oc/18/870_801...,literal,Ordinanza sull'esercizio della Fabbrica federa...,literal,1901-11-09,literal,1901-11-09,literal,it,Ordinanza del Consiglio federale,NaN,NaN
4,uri,https://fedlex.data.admin.ch/eli/oc/19/816_779...,literal,Decreto del Consiglio federale del 24 dicembre...,literal,1906-07-01,literal,1906-07-01,literal,it,Ordinanza del Consiglio federale,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46852,uri,https://fedlex.data.admin.ch/eli/cc/2024/142,literal,Ordinanza della FINMA del 6 marzo 2024 sui ris...,literal,2024-04-05,literal,2025-01-01,literal,it,Atto legislativo delle aziende e degli stabili...,NaN,NaN
46853,uri,https://fedlex.data.admin.ch/eli/cc/2024/331,literal,Legge federale del 30 settembre 2022 sulla pro...,literal,2024-07-02,literal,2025-01-01,literal,it,Legge federale,NaN,NaN
46854,uri,https://fedlex.data.admin.ch/eli/cc/2024/493,literal,Ordinanza del 28 agosto 2024 sull’adeguamento ...,literal,2024-09-13,literal,2025-01-01,literal,it,Ordinanza del Consiglio federale,NaN,NaN
46855,uri,https://fedlex.data.admin.ch/eli/cc/2024/685,literal,Ordinanza del 13 novembre 2024 sulla cooperazi...,literal,2024-11-25,literal,2025-01-01,literal,it,Ordinanza del Consiglio federale,NaN,NaN
46856,uri,https://fedlex.data.admin.ch/eli/cc/2024/698,literal,Ordinanza del 20 novembre 2024 concernente l’a...,literal,2024-11-26,literal,2025-01-01,literal,it,Ordinanza del Consiglio federale,NaN,NaN

In [5]:
# data filtered by keeping only the rows with a corresponding pdf file
df_pdf = df[df['fileUrl.value'].notna()]
df_pdf = df_pdf[df_pdf['fileUrl.value'].str.contains('.pdf')]

# display the number of laws per publication year
df_countYear = df_pdf
df_countYear['publicationDate.value'] = df_countYear['publicationDate.value'].str[:4]
print(df_countYear['publicationDate.value'].value_counts().sort_index(ascending=False))

print("------------------------------------------------------------------------------------")

# display the number of laws per type of document
df_countType = df_pdf
df_countType['typeDoc.value'] = df_countType['typeDoc.value']
print(df_countType['typeDoc.value'].value_counts())

publicationDate.value
2025      10
2024     844
2023     870
2022     902
2021     932
2020    1058
2019     779
2018     812
2017     833
2016     825
2015     916
2014     782
2013     875
2012     890
2011     895
2010     894
2009     838
2008     874
2007     922
2006     852
2005     801
2004     806
2003     750
2002     691
2001     521
2000     550
1999     530
1998     163
Name: count, dtype: int64
------------------------------------------------------------------------------------
typeDoc.value
Ordinanza del Consiglio federale                                                 5959
Ordinanza di un dipartimento                                                     3577
Ordinanza di un'ufficio                                                          2935
Campo d'applicazione                                                             2827
Trattato internazionale bilaterale                                               1871
Trattato internazionale multilaterale                                            1033
Legge federale                                                                   1011
Correzione RU                                                                     954
Comunicazione di abrogazioni (testo divenuto privo d'oggetto) o modificazioni     296
Atto legislativo delle aziende e degli stabilimenti autonomi                      226
Atto legislativo dei Tribunali federali                                           127
Decreti federali che sottostanno a referendum facoltativo (trattati)              117
Decreto del Consiglio federale                                                    103
Ordinanza dell'Assemblea federale                                                  88
Legge federale urgente                                                             55
Trattati tra Confederazione e Cantoni                                              46
Decreti federali che sottostanno a referendum obbligatorio                         43
Convenzioni delle aziende e degli stabilimenti autonomi                            27
Decreti federali che sottostanno a referendum facoltativo (altri)                  22
Atto legislativo del Consiglio nazionale                                           19
Istruzioni del Consiglio federale                                                  15
Atto legislativo di Commissioni                                                    15
Atto legislativo del Consiglio degli Stati                                         13
Decreto federale semplice (approvazione di trattati)                                8
Decreto federale semplice (altri)                                                   7
Correzione FF                                                                       5
Decisioni delle autorità                                                            4
Convenzioni del Consiglio federale                                                  4
Strategia e obiettivi                                                               2
Concessioni                                                                         2
Comunicazione                                                                       1
Legge federale urgente che sottostanno a referendum obbligatorio                    1
Rapporto del Consiglio federale                                                     1
Garanzia alle costituzioni cantonali                                                1
Name: count, dtype: int64

In [6]:
# keep only the acts without a corresponding pdf file
df = pd.read_csv("./raw_data/allActsPDF.csv")
df_no_pdf = df[df['fileUrl.value'].isna()]

# display the number of laws per publication year
df_countYear = df_no_pdf
df_countYear['publicationDate.value'] = df_countYear['publicationDate.value'].str[:4]
print(df_countYear['publicationDate.value'].value_counts().sort_index(ascending=False))

print("------------------------------------------------------------------------------------")

# display the number of laws per type of document
df_countType = df_no_pdf
df_countType['typeDoc.value'] = df_countType['typeDoc.value']
print(df_countType['typeDoc.value'].value_counts())

publicationDate.value
2025      1
2024    106
2023    150
2022    131
2021    169
       ...
1852      1
1851      2
1850      4
1849      2
1848      1
Name: count, Length: 159, dtype: int64
------------------------------------------------------------------------------------
typeDoc.value
Ordinanza del Consiglio federale                                                 10177
Ordinanza di un dipartimento                                                      4263
Trattato internazionale bilaterale                                                2578
Campo d'applicazione                                                              1886
Trattato internazionale multilaterale                                             1591
Legge federale                                                                    1076
Ordinanza di un'ufficio                                                            739
Correzione RU                                                                      726
Atto legislativo delle aziende e degli stabilimenti autonomi                       575
Decreti federali che sottostanno a referendum facoltativo (altri)                  431
Trattati tra Confederazione e Cantoni                                              292
Decreto federale semplice (altri)                                                  225
Ordinanza dell'Assemblea federale                                                  208
Legge federale urgente                                                             146
Atto legislativo di Commissioni                                                    107
Decreti federali che sottostanno a referendum facoltativo (trattati)               100
Decreti federali che sottostanno a referendum obbligatorio                          90
Atto legislativo dei Tribunali federali                                             79
Comunicazione di abrogazioni (testo divenuto privo d'oggetto) o modificazioni       58
Decreto federale semplice (approvazione di trattati)                                53
Atto legislativo del Consiglio nazionale                                            18
Atto legislativo del Consiglio degli Stati                                          12
Garanzia alle costituzioni cantonali                                                 7
Decreto del Consiglio federale                                                       4
Costituzione cantonale                                                               1
Name: count, dtype: int64

/tmp/ipykernel_1130605/4081224064.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_countYear['publicationDate.value'] = df_countYear['publicationDate.value'].str[:4]
/tmp/ipykernel_1130605/4081224064.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_countType['typeDoc.value'] = df_countType['typeDoc.value']

In [10]:
df_pdf = pd.read_csv("./raw_data/acts_pdf.csv")
df_pdf

,act.type,act.value,title.type,title.value,publicationDate.type,publicationDate.value,entryintoforce.type,entryintoforce.value,typeDoc.type,typeDoc.xml:lang,typeDoc.value,fileUrl.type,fileUrl.value
0,uri,https://fedlex.data.admin.ch/eli/oc/2005/100,literal,Convenzione per l'istituzione dell'Organizzazi...,literal,08.02.2005,literal,18.04.1951,literal,it,Trattato internazionale multilaterale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
1,uri,https://fedlex.data.admin.ch/eli/oc/1999/190,literal,Decreto federale concernente una riserva alla ...,literal,20.04.1999,literal,20.03.1967,literal,it,Decreto federale semplice (approvazione di tra...,uri,https://fedlex.data.admin.ch/filestore/fedlex....
2,uri,https://fedlex.data.admin.ch/eli/oc/2010/812,literal,Convenzione europea di estradizione,literal,07.12.2010,literal,20.03.1967,literal,it,Correzione RU,uri,https://fedlex.data.admin.ch/filestore/fedlex....
3,uri,https://fedlex.data.admin.ch/eli/oc/2012/168,literal,Scambio di note del 20 dicembre 1967/28 febbra...,literal,13.03.2012,literal,28.02.1968,literal,it,Trattato internazionale bilaterale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
4,uri,https://fedlex.data.admin.ch/eli/oc/2008/688,literal,Comunicazione concernente un accordo internazi...,literal,04.11.2008,literal,19.08.1969,literal,it,Comunicazione di abrogazioni (testo divenuto p...,uri,https://fedlex.data.admin.ch/filestore/fedlex....
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21410,uri,https://fedlex.data.admin.ch/eli/oc/2024/688,literal,Ordinanza concernente gli effettivi massimi pe...,literal,25.11.2024,literal,01.01.2025,literal,it,Ordinanza del Consiglio federale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
21411,uri,https://fedlex.data.admin.ch/eli/oc/2024/692,literal,Ordinanza concernente l’imposizione minima dei...,literal,26.11.2024,literal,01.01.2025,literal,it,Ordinanza del Consiglio federale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
21412,uri,https://fedlex.data.admin.ch/eli/oc/2024/693,literal,Ordinanza sulla costituzione di una riserva di...,literal,26.11.2024,literal,01.01.2025,literal,it,Ordinanza del Consiglio federale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
21413,uri,https://fedlex.data.admin.ch/eli/oc/2024/697,literal,Ordinanza sull’assicurazione malattie (OAMal),literal,26.11.2024,literal,01.01.2025,literal,it,Ordinanza del Consiglio federale,uri,https://fedlex.data.admin.ch/filestore/fedlex....
21414,uri,https://fedlex.data.admin.ch/eli/oc/2024/698,literal,Ordinanza del 20 novembre 2024 concernente l’a...,literal,26.11.2024,literal,01.01.2025,literal,it,Ordinanza del Consiglio federale,uri,https://fedlex.data.admin.ch/filestore/fedlex....

In [ ]:
import fitz

pdf = fitz.open('./LawsDocs/PDFs_PageCodes/1998/2009_01.09_Ordinanza del Consiglio federale.pdf')
out = ""
for page in pdf:
    blocks = page.get_text("dict")["blocks"]

    for block in blocks:
        if "lines" in block:
            for line in block["lines"]:
                for span in line["spans"]:
                    text = span["text"].strip()
                    font_size = span["size"]
                    font_name = span["font"]
                    is_bold = "Bold" in font_name or "bold" in font_name

                    if not text:
                        continue

                    # Detect Headers (Chapters)
                    if font_size > 14:  # Adjust threshold if needed
                        formatted_text = f"# {text}\n"
                    elif font_size > 12:
                        formatted_text = f"## {text}\n"
                    elif is_bold:
                        formatted_text = f"**{text}**"
                    elif text.startswith("Art.") or text.startswith("Allegato"):
                        formatted_text = f"### {text}\n"
                    elif text[0].isdigit():  # Numbered lists
                        formatted_text = f"- {text}"
                    else:
                        formatted_text = text

        out += formatted_text + "\n"

out += "\n"

with open("output.md", "w") as file:
    file.write(out)

In [5]:
import pandas as pd
from collections import defaultdict

# Load the CSV file
df_pdf = pd.read_csv("./raw_data/allActsPDF.csv")

# Extract the last two elements after splitting on '/'
df_pdf["processed_value"] = df_pdf["act.value"].astype(str).str.split('/').str[-2:].str.join('/')

# Find duplicate rows based on this processed value
duplicate_indices_pdf = df_pdf[df_pdf.duplicated("processed_value", keep=False)].index

# Group indices by their processed values
duplicate_groups_pdf = defaultdict(list)
for idx, value in df_pdf.loc[duplicate_indices_pdf, "processed_value"].items():
    duplicate_groups_pdf[value].append(idx)

# Convert to DataFrame for saving
grouped_df_pdf = pd.DataFrame([(key, indices) for key, indices in duplicate_groups_pdf.items()], columns=["Processed_Value", "Indices"])

# Save to CSV
grouped_df_pdf.to_csv("duplicate_indices_pdf.csv", index=False)

print(grouped_df_pdf)

    Processed_Value         Indices
0          2023/402  [29826, 29927]
1          2021/123  [32924, 33055]
2          2021/124  [34479, 34502]
3          2012/291  [34857, 35454]
4          2021/126  [35296, 35321]
..              ...             ...
594        2024/142  [46810, 46852]
595        2024/331  [46817, 46853]
596        2024/493  [46830, 46854]
597        2024/685  [46833, 46855]
598        2024/698  [46840, 46856]

[599 rows x 2 columns]

In [7]:
df_dup = pd.read_csv("duplicate_indices_pdf.csv")
indices = df_dup['Indices'].tolist()
# take all the values in the square brackets and put them in a list
indices_to = [int(i) for sublist in indices for i in sublist[1:-1].split(", ")]
indices.__len__(), indices_to.__len__()

(599, 1207)